APP_VERSION = "0.5.0rc2"

MANAGED_PLAYLIST_DESCRIPTION = (
    "Randomized by RoyalShuffle | Spotify Companion"
)

# Retain recognition of outputs created before the description text changed.
LEGACY_MANAGED_PLAYLIST_DESCRIPTION = "True-randomized copy generated by RoyalShuffle"
