"""Balanced Opportunity delivery workflow; UI-independent and ID-based."""
from dataclasses import dataclass
from copy import deepcopy
from delivery_receipts import delivery_plan, validate_delivery

from auth import log_debug

from requests import HTTPError

from opportunity import prepare_deal
from opportunity_state import OpportunityStore, candidate_rotation
import playlist_registry as registry
from writer_lock import writer_lock
from spotify_client import SpotifyRetryLaterError


OPPORTUNITY_PLAYLIST_DESCRIPTION = "Balanced Opportunity deal generated by RoyalShuffle"


class PendingSessionError(RuntimeError):
    """A saved operation must be resumed rather than freshly dealt."""


class UnknownCreationError(PendingSessionError):
    """Creation may have succeeded, but no durable output ID is available."""


@dataclass(frozen=True)
class OpportunityResult:
    source_id: str
    output_id: str
    output_name: str
    uris: tuple[str, ...]
    progress: dict


def _is_404(exc):
    return isinstance(exc, HTTPError) and getattr(exc.response, "status_code", None) == 404


def _creation_name(callback, default):
    if callback is None:
        raise ValueError("Opportunity creation requires an output-name callback.")
    chosen = callback(default)
    if chosen is None:
        return None
    if not isinstance(chosen, str) or not chosen.strip():
        raise ValueError("Playlist name cannot be empty")
    return chosen.strip()


class OpportunityWorkflow:
    def __init__(self, spotify, store=None):
        self.spotify = spotify
        self.store = store if store is not None else OpportunityStore()
        if self.store.path.parent.resolve() != registry.REGISTRY_FILE.parent.resolve():
            raise ValueError("Opportunity state and registry must share a user-data location.")

    def _resolve(self, output_id, *, direct=False):
        if output_id is None:
            return None
        playlist = None if direct else next((p for p in self.spotify.get_playlists()
                                             if p.get("id") == output_id), None)
        if playlist is None:
            try:
                playlist = self.spotify.get_playlist(output_id)
            except Exception as exc:
                if _is_404(exc):
                    return None
                raise
        if (not isinstance(playlist, dict) or playlist.get("id") != output_id
                or not isinstance(playlist.get("name"), str)):
            raise ValueError("Managed output lookup returned an invalid identity or name.")
        return playlist

    def generate_next_session(self, source_id, *, output_name_callback=None,
                              artist_separation=False, rng=None, source_name=None):
        return self._generate(source_id, False, output_name_callback, artist_separation, rng, source_name)

    def start_new_rotation(self, source_id, *, output_name_callback=None,
                           artist_separation=False, rng=None, source_name=None,
                           abandon_pending_operation_id=None):
        """Call only after the UI has obtained abandonment confirmation."""
        return self._generate(source_id, True, output_name_callback, artist_separation, rng, source_name,
                              abandon_pending_operation_id)

    def _default_name(self, source_id, active, source_name):
        if source_name is None:
            source = self.spotify.get_playlist(source_id)
            if not isinstance(source, dict) or source.get("id") != source_id:
                raise ValueError("Source lookup returned an invalid identity.")
            source_name = source.get("name")
        if not isinstance(source_name, str) or not source_name.strip():
            raise ValueError("A source name is required for deal naming.")
        return f'{source_name} - Deal {active["completed_sessions"] + 1}'

    def _check_output(self, source_id, output_id):
        state = self.store.load()
        if (output_id in state["sources"]
                or output_id in registry.load_managed_playlist_ids()
                or any(other != source_id and source["pending"] is not None
                       and source["pending"]["output_id"] == output_id
                       for other, source in state["sources"].items())):
            raise PendingSessionError("Pending output conflicts with a source or managed output; recovery stopped.")

    def _generate(self, source_id, start_new, callback, artist_separation, rng, source_name,
                  abandon_pending_operation_id=None):
        with writer_lock(self.store.path.parent):
            state = self.store.load()
            source = state["sources"].get(source_id)
            pending = source["pending"] if source else None
            if pending is not None:
                if not start_new or abandon_pending_operation_id != pending["operation_id"]:
                    raise PendingSessionError("Resume the pending session or confirm its abandonment.")
            elif abandon_pending_operation_id is not None:
                raise PendingSessionError("Pending operation changed; confirm abandonment again.")
            if source_id in registry.load_managed_playlist_ids():
                raise ValueError("Managed outputs cannot be Opportunity sources.")
            active = source["active"] if source else None
            candidate = None
            if start_new or active is None or not active["undealt"]:
                items = self.spotify.get_playlist_items(source_id)
                eligible = [item for item in items if not item.get("is_local", False)
                            and not (isinstance(item.get("uri"), str)
                                     and item["uri"].startswith("spotify:local:"))]
                candidate = candidate_rotation(eligible)
            selected_from = candidate if candidate is not None else active
            deal = prepare_deal(source_id, selected_from,
                                artist_separation=artist_separation, rng=rng)
            name = _creation_name(callback, self._default_name(source_id, selected_from, source_name))
            if name is None:
                return None
            pending = self.store.stage_pending(deal, candidate=candidate, creation_name=name,
                                               replace_pending_operation_id=abandon_pending_operation_id)
            return self._deliver(source_id, pending, None)

    def _update(self, source_id, pending, **changes):
        return self.store.update_pending(source_id, pending["operation_id"], **changes)

    def _ensure_output(self, source_id, pending, playlist):
        output_id = pending["output_id"]
        if output_id is None:
            # Persist intent before creation. A crash/lost response here must
            # never automatically retry creation with unknown identity.
            pending = self._update(source_id, pending, phase="creating")
            try:
                created = self.spotify.create_playlist(
                    pending["creation_name"], description=OPPORTUNITY_PLAYLIST_DESCRIPTION, public=False)
            except SpotifyRetryLaterError:
                # The client raises this only after known HTTP 429 rejections:
                # no successful creation or unknown response needs recovery.
                self._update(source_id, pending, phase="staged")
                raise
            except HTTPError as exc:
                status = getattr(exc.response, "status_code", None)
                if type(status) is int and 400 <= status < 500:
                    self._update(source_id, pending, phase="staged")
                raise
            output_id = created.get("id") if isinstance(created, dict) else None
            if (not isinstance(output_id, str) or not output_id.isascii()
                    or not output_id.isalnum() or output_id == source_id):
                raise UnknownCreationError("Created output identity is unknown; automatic retry stopped.")
            try:
                pending = self._update(source_id, pending, output_id=output_id, phase="output_known")
            except Exception as exc:
                raise UnknownCreationError(
                    f"Output {output_id} was returned but could not be saved; automatic retry stopped."
                ) from exc
            playlist = {"id": output_id, "name": pending["creation_name"]}
        self._check_output(source_id, output_id)
        return pending, playlist

    def _finalize(self, source_id, pending, playlist, *, exact_readback=False):
        if exact_readback:
            pending = self._update(source_id, pending, delivery=None)
        elif pending["delivery"] is None or not validate_delivery(
                pending["delivery"], pending["operation_id"], pending["output_id"], pending["uris"]):
            raise PendingSessionError("Complete delivery evidence required.")
        pending = self._update(source_id, pending, phase="delivered")
        result = self.store.finalize_pending(source_id, pending["operation_id"])
        return OpportunityResult(source_id, pending["output_id"], playlist["name"],
                                 tuple(pending["uris"]), result)

    def _deliver(self, source_id, pending, playlist):
        pending, playlist = self._ensure_output(source_id, pending, playlist)
        evidence = delivery_plan(pending["operation_id"], pending["output_id"], pending["uris"])
        pending = self._update(source_id, pending, phase="populating", delivery=evidence)
        def persist_receipt(receipt):
            nonlocal pending
            updated = deepcopy(pending["delivery"])
            updated["receipts"].append(receipt)
            pending = self._update(source_id, pending, delivery=updated)
        self.spotify.submit_opportunity_deal(evidence, list(pending["uris"]), persist_receipt)
        if not validate_delivery(pending["delivery"], pending["operation_id"], pending["output_id"], pending["uris"]):
            raise PendingSessionError("Delivery acknowledgments are incomplete; recovery required.")
        return self._finalize(source_id, pending, playlist)

    def resume_pending_session(self, source_id, *, output_name_callback=None, source_name=None):
        with writer_lock(self.store.path.parent):
            pending = self.store.pending(source_id)
            if pending is None:
                raise PendingSessionError("No pending session to resume.")
            if pending["delivery"] is not None and validate_delivery(
                    pending["delivery"], pending["operation_id"], pending["output_id"], pending["uris"]):
                # Submission already proved; edits/deletion cannot undo it.
                return self._finalize(source_id, pending, {"name": pending["creation_name"]})
            if pending["phase"] == "creating" and pending["output_id"] is None:
                raise UnknownCreationError(
                    "Creation may have succeeded without a saved ID. Automatic retry is unsafe.")
            output_id = pending["output_id"]
            if output_id is None:
                return self._deliver(source_id, pending, None)
            if pending["creation_name"] is None:
                # Old acceptance builds could stage a reused completed playlist.
                # Keep its contents intact and deliver the saved deal to a fresh ID.
                source = self.store.load()["sources"][source_id]
                selected_from = pending["candidate"] or source["active"]
                name = _creation_name(output_name_callback,
                                      self._default_name(source_id, selected_from, source_name))
                if name is None:
                    return None
                pending = self._update(source_id, pending, output_id=None, phase="staged", delivery=None,
                                       creation_name=name, stale_output_id=output_id)
                return self._deliver(source_id, pending, None)
            self._check_output(source_id, output_id)
            playlist = self._resolve(output_id)
            if playlist is not None:
                try:
                    actual = self.spotify.get_playlist_items_raw(output_id)
                except Exception as exc:
                    if not _is_404(exc):
                        raise
                    # A read-back 404 is confirmed again by exact-ID lookup.
                    playlist = self._resolve(output_id, direct=True)
                    if playlist is not None:
                        raise PendingSessionError("Output identity changed during verification; retry later.") from exc
                else:
                    if actual == pending["uris"]:
                        pending, playlist = self._ensure_output(source_id, pending, playlist)
                        return self._finalize(source_id, pending, playlist, exact_readback=True)
                    log_debug(f"Opportunity pending readback differs; operation_id={pending['operation_id']}; "
                              f"output_playlist_id={output_id}; expected_count={len(pending['uris'])}; "
                              f"actual_count={len(actual)}; resubmitting saved prepared deal")
                    return self._deliver(source_id, pending, playlist)
            # Confirmed-404 replacement changes only delivery identity/name.
            # The saved URI order and candidate remain untouched.
            name = _creation_name(output_name_callback, pending["creation_name"])
            if name is None:
                return None
            pending = self._update(source_id, pending, output_id=None, phase="staged", delivery=None,
                                   creation_name=name, stale_output_id=output_id)
            return self._deliver(source_id, pending, None)
