import ctypes
import os
import re
import sys
import tkinter as tk
import threading
import traceback

from auth import (
    start_authentication, 
    finish_authentication,
    wait_for_spotify_callback,
    save_token_data,
    load_token_data,
    refresh_access_token,
    clear_token_data,
    log_debug,
)

from spotify_client import SpotifyClient, SpotifyRetryLaterError
from playlist_export import export_playlist_csv
from playlist_import import (
    PlaylistImportValidationError,
    parse_playlist_csv,
)
from playlist_import_workflow import (
    CatalogValidationError,
    PlaylistImportPartialWriteError,
    create_imported_playlist,
    preflight_playlist_import,
)
from royalshuffle import royal_shuffle
from playlist_registry import (
    add_managed_playlist_id,
    add_reviewed_legacy_playlist_id,
    load_managed_playlist_ids,
    load_reviewed_legacy_playlist_ids,
)
from pathlib import Path
from tkinter import filedialog, messagebox, simpledialog

from app_paths import ensure_exports_folder, ensure_royalshuffle_folder

LAST_PLAYLIST_FILE = Path.home() / ".royalshuffle_last_playlist"
LEGACY_PLAYLIST_DESCRIPTION = (
    "True-randomized copy generated by RoyalShuffle"
)
OPEN_FOLDER_ERROR_MESSAGE = (
    "RoyalShuffle couldn't open its folder. Please try again."
)
WINDOW_ICON_RELATIVE_PATH = Path("assets") / "royalshuffle.ico"


def application_asset_path(relative_path):
    return Path(__file__).resolve().parent / relative_path


def configure_window_icon(root):
    try:
        root.iconbitmap(
            str(application_asset_path(WINDOW_ICON_RELATIVE_PATH))
        )
    except Exception as exc:
        log_debug(
            "RoyalShuffle window icon could not be loaded; "
            f"exception_type={type(exc).__name__}"
        )


def application_version_text():
    if not getattr(sys, "frozen", False):
        return "Development build"

    try:
        version_api = ctypes.WinDLL("version", use_last_error=True)
        version_api.GetFileVersionInfoSizeW.argtypes = [
            ctypes.c_wchar_p,
            ctypes.POINTER(ctypes.c_uint),
        ]
        version_api.GetFileVersionInfoSizeW.restype = ctypes.c_uint
        version_api.GetFileVersionInfoW.argtypes = [
            ctypes.c_wchar_p,
            ctypes.c_uint,
            ctypes.c_uint,
            ctypes.c_void_p,
        ]
        version_api.GetFileVersionInfoW.restype = ctypes.c_int
        version_api.VerQueryValueW.argtypes = [
            ctypes.c_void_p,
            ctypes.c_wchar_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_uint),
        ]
        version_api.VerQueryValueW.restype = ctypes.c_int

        version_size = version_api.GetFileVersionInfoSizeW(
            sys.executable,
            None,
        )
        if not version_size:
            raise OSError(ctypes.get_last_error())

        version_data = ctypes.create_string_buffer(version_size)
        if not version_api.GetFileVersionInfoW(
            sys.executable,
            0,
            version_size,
            version_data,
        ):
            raise OSError(ctypes.get_last_error())

        translation_pointer = ctypes.c_void_p()
        translation_length = ctypes.c_uint()
        if not version_api.VerQueryValueW(
            version_data,
            r"\VarFileInfo\Translation",
            ctypes.byref(translation_pointer),
            ctypes.byref(translation_length),
        ):
            raise OSError(ctypes.get_last_error())
        if translation_length.value < 4:
            raise ValueError("Version translation is incomplete")

        translation = ctypes.cast(
            translation_pointer,
            ctypes.POINTER(ctypes.c_ushort),
        )
        language, code_page = translation[0], translation[1]
        product_version_path = (
            f"\\StringFileInfo\\{language:04x}{code_page:04x}"
            "\\ProductVersion"
        )

        product_version_pointer = ctypes.c_void_p()
        product_version_length = ctypes.c_uint()
        if not version_api.VerQueryValueW(
            version_data,
            product_version_path,
            ctypes.byref(product_version_pointer),
            ctypes.byref(product_version_length),
        ):
            raise OSError(ctypes.get_last_error())

        product_version = ctypes.wstring_at(
            product_version_pointer.value,
            product_version_length.value,
        ).rstrip("\0")
        if not product_version:
            raise ValueError("ProductVersion is empty")

        return f"v{product_version}"
    except (OSError, TypeError, ValueError):
        return "Version unavailable"


def safe_csv_filename(playlist_name):
    filename = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", playlist_name)
    filename = filename.strip().rstrip(".")
    filename = filename or "playlist"

    reserved_names = {
        "CON", "PRN", "AUX", "NUL",
        *(f"COM{number}" for number in range(1, 10)),
        *(f"LPT{number}" for number in range(1, 10)),
    }
    if filename.upper() in reserved_names:
        filename = "_" + filename

    return filename


def choose_csv_destination(parent, playlist_name):
    dialog_options = {
        "title": "Export playlist as CSV",
        "initialfile": safe_csv_filename(playlist_name) + ".csv",
        "defaultextension": ".csv",
        "filetypes": [
            ("CSV files", "*.csv"),
            ("All files", "*.*"),
        ],
        "parent": parent,
    }

    exports_directory = ensure_exports_folder()
    if exports_directory is not None:
        dialog_options["initialdir"] = str(exports_directory)

    return filedialog.asksaveasfilename(**dialog_options)


def choose_csv_source(parent):
    return filedialog.askopenfilename(
        title="Import playlist from CSV",
        filetypes=[
            ("CSV files", "*.csv"),
            ("All files", "*.*"),
        ],
        parent=parent,
    )


def _format_import_issues(issues):
    lines = []
    for issue in issues:
        location = (
            f"Row {issue.line_number}"
            if issue.line_number is not None
            else "CSV"
        )
        lines.append(f"{location}: {issue.message}")
    return "\n".join(lines)


def import_csv_playlist(parent, spotify, status_label, import_button):
    source = choose_csv_source(parent)
    if not source:
        return None

    import_button.config(state="disabled")
    status_label.config(text="Validating CSV import...")
    parent.update_idletasks()

    try:
        rows = parse_playlist_csv(source)
        prepared_import = preflight_playlist_import(spotify, rows)
        status_label.config(
            text=f"{len(rows)} tracks found, {len(rows)} valid"
        )
        parent.update_idletasks()

        playlist_name = simpledialog.askstring(
            "Import CSV",
            "Name your imported playlist:",
            parent=parent,
        )
        if playlist_name is None:
            return None

        playlist_name = playlist_name.strip()
        if not playlist_name:
            status_label.config(text="Playlist name cannot be empty")
            return None

        status_label.config(text=f"Creating: {playlist_name}...")
        parent.update_idletasks()
        result = create_imported_playlist(
            spotify,
            prepared_import,
            playlist_name,
        )
        status_label.config(
            text=f"Created: {result.name} • {result.item_count} tracks"
        )
        return result
    except (PlaylistImportValidationError, CatalogValidationError) as exc:
        messagebox.showerror(
            "CSV Import Validation",
            _format_import_issues(exc.issues),
            parent=parent,
        )
        status_label.config(
            text=f"CSV import found {len(exc.issues)} invalid row(s)"
        )
        return None
    except PlaylistImportPartialWriteError as exc:
        status_label.config(
            text=(
                f"Partially created: {exc.playlist_name} • "
                f"{exc.items_written}/{exc.total_items} tracks added"
            )
        )
        messagebox.showerror(
            "CSV Import Incomplete",
            (
                f'Playlist "{exc.playlist_name}" was partially created.\n\n'
                f"{exc.items_written} of {exc.total_items} tracks were added. "
                "The remaining tracks were not added. The partial private "
                "playlist was left in Spotify."
            ),
            parent=parent,
        )
        return None
    except SpotifyRetryLaterError as exc:
        status_label.config(text=str(exc))
        return None
    except Exception as exc:
        log_debug(
            "CSV import operational failure; "
            f"exception_type={type(exc).__name__}"
        )
        status_label.config(
            text="CSV import failed. No playlist was created."
        )
        return None
    finally:
        import_button.config(state="normal")


def open_royalshuffle_folder(parent):
    folder = ensure_royalshuffle_folder()
    if folder is None:
        log_debug(
            "RoyalShuffle user folder could not be resolved or created"
        )
        messagebox.showerror(
            "Open RoyalShuffle Folder",
            OPEN_FOLDER_ERROR_MESSAGE,
            parent=parent,
        )
        return

    try:
        os.startfile(str(folder))
    except OSError as exc:
        log_debug(
            "RoyalShuffle user folder open failed; "
            f"exception_type={type(exc).__name__}; "
            f"winerror={getattr(exc, 'winerror', None)}"
        )
        messagebox.showerror(
            "Open RoyalShuffle Folder",
            OPEN_FOLDER_ERROR_MESSAGE,
            parent=parent,
        )


def create_open_folder_button(parent):
    button = tk.Button(
        parent,
        text="Open RoyalShuffle Folder",
        font=("Arial", 8),
        command=lambda: open_royalshuffle_folder(parent),
    )
    button.place(relx=1.0, x=-10, y=10, anchor="ne")
    return button


def create_import_csv_button(parent, command):
    button = tk.Button(
        parent,
        text="Import CSV...",
        width=20,
        state="disabled",
        command=command,
    )
    button.pack(side="left", padx=5)
    return button


def review_legacy_playlists(playlists, parent):
    managed_playlist_ids = load_managed_playlist_ids()
    reviewed_playlist_ids = load_reviewed_legacy_playlist_ids()

    candidates = [
        playlist
        for playlist in playlists
        if playlist["id"] not in managed_playlist_ids
        and playlist["id"] not in reviewed_playlist_ids
        and playlist.get("description")
        == LEGACY_PLAYLIST_DESCRIPTION
    ]

    for playlist in candidates:
        recover = messagebox.askyesno(
            "Recover RoyalShuffle playlist?",
            (
                "RoyalShuffle found a possible playlist from an "
                "earlier version.\n\n"
                f'Playlist: {playlist["name"]}\n'
                f'ID: {playlist["id"]}\n\n'
                "Recover this playlist as managed by RoyalShuffle?\n\n"
                "Choose No if this is an ordinary playlist. It will "
                "remain untouched and available as a source."
            ),
            parent=parent,
        )

        if recover:
            add_managed_playlist_id(playlist["id"])

        add_reviewed_legacy_playlist_id(playlist["id"])

def load_spotify_session(
    access_token,
    status_label,
    connect_button,
    playlist_listbox,
    eligible_playlists,
    client_state,
    selected_playlist_state,
    royal_shuffle_button,
    export_csv_button,
    import_csv_button,
):
    log_debug("Creating Spotify client session")
    client = SpotifyClient(access_token)
    client_state["client"] = client

    log_debug("Fetching Spotify playlists")
    playlists = client.get_playlists()
    log_debug(f"Spotify playlist fetch succeeded; count={len(playlists)}")

    review_legacy_playlists(
        playlists,
        playlist_listbox.winfo_toplevel(),
    )

    managed_playlist_ids = load_managed_playlist_ids()
    eligible_playlists.clear()
    eligible_playlists.extend([
        playlist
        for playlist in playlists
        if playlist["id"] not in managed_playlist_ids
    ])

    playlist_listbox.config(state="normal")
    import_csv_button.config(state="normal")
    playlist_listbox.delete(0, tk.END)

    for playlist in eligible_playlists:
        playlist_listbox.insert(
            tk.END,
            playlist["name"],
        )

    if LAST_PLAYLIST_FILE.exists():
        last_playlist_id = LAST_PLAYLIST_FILE.read_text().strip()

        for index, playlist in enumerate(eligible_playlists):
            if playlist["id"] == last_playlist_id:
                playlist_listbox.selection_set(index)
                playlist_listbox.activate(index)
                playlist_listbox.see(index)

                selected_playlist_state["playlist"] = playlist

                status_label.config(
                    text=f'Selected: {playlist["name"]}'
                )

                royal_shuffle_button.config(
                    state="normal"
                )
                export_csv_button.config(
                    state="normal"
                )

                connect_button.config(state="disabled")
                return

    status_label.config(
        text="Connected to Spotify • Select a playlist"
    )

    connect_button.config(state="disabled")

def connect_spotify(
    status_label,
    connect_button,
    playlist_listbox,
    eligible_playlists,
    client_state,
    selected_playlist_state,
    royal_shuffle_button,
    export_csv_button,
    import_csv_button,
):
    log_debug("Connect Spotify button pressed")

    callback_state = {
        "url": None,
        "error": None,
    }

    def listen_for_callback():
        try:
            callback_state["url"] = wait_for_spotify_callback()
        except Exception as exc:
            callback_state["error"] = exc
            log_debug(
                "Spotify callback listener exception:\n"
                + traceback.format_exc()
            )

    listener_thread = threading.Thread(
        target=listen_for_callback,
        daemon=True,
    )
    listener_thread.start()

    auth_session = start_authentication()
    log_debug("Spotify browser authorization started")

    status_label.config(
        text="Waiting for Spotify authorization..."
    )

    connect_button.config(state="disabled")

    def finish_connection(callback_url):
        print("DEBUG: finishing authentication")
        log_debug("UI received Spotify callback; finishing connection")

        try:
            token_data = finish_authentication(
                callback_url,
                auth_session["code_verifier"],
                auth_session["state"],
            )

            log_debug("OAuth token data returned to UI")
            save_token_data(token_data)

            access_token = token_data["access_token"]

            log_debug("Loading Spotify session after authentication")
            load_spotify_session(
                access_token,
                status_label,
                connect_button,
                playlist_listbox,
                eligible_playlists,
                client_state,
                selected_playlist_state,
                royal_shuffle_button,
                export_csv_button,
                import_csv_button,
            )
            log_debug("Spotify connection completed successfully")

        except SpotifyRetryLaterError as exc:
            log_debug(
                "Spotify connection deferred; "
                f"exception_type={type(exc).__name__}"
            )
            status_label.config(text=str(exc))
            connect_button.config(state="normal")

        except Exception as exc:
            print(
                f"Spotify automatic login failed: {exc!r}"
            )
            log_debug(
                "Spotify connection failed:\n"
                + traceback.format_exc()
            )

            clear_token_data()

            status_label.config(
                text="Not connected"
            )

            connect_button.config(
                state="normal"
            )

    def check_for_callback():
        if callback_state["error"] is not None:
            print(
                "Spotify callback listener failed: "
                f'{callback_state["error"]!r}'
            )

            status_label.config(
                text="Spotify connection failed. Click Connect Spotify to retry."
            )

            connect_button.config(state="normal")
            return

        if callback_state["url"] is not None:
            finish_connection(
                callback_state["url"]
            )
            return

        status_label.after(
            100,
            check_for_callback,
        )

    check_for_callback()

def main():
    root = tk.Tk()
    configure_window_icon(root)
    root.title("RoyalShuffle")
    root.geometry()
    root.minsize(500, 500)

    version_label = tk.Label(
        root,
        text=application_version_text(),
        font=("Arial", 8),
        fg="#777777",
    )
    version_label.place(x=10, y=10, anchor="nw")

    create_open_folder_button(root)

    title = tk.Label(
        root,
        text="RoyalShuffle",
        font=("Arial", 24)
    )
    title.pack(pady=20)

    subtitle = tk.Label(
        root,
        text="Transparent, user-controlled Spotify shuffle"
    )
    subtitle.pack(pady=10)
    status_label = tk.Label(
        root,
        text="Not connected"
    )
    status_label.pack(pady=10)

    connect_button = tk.Button(
        root,
        text="Connect Spotify",
        width=20,
        height=2,
        font=("Arial", 11),
        command=lambda: connect_spotify(
            status_label,
            connect_button,
            playlist_listbox,
            eligible_playlists,
            client_state,
            selected_playlist_state,
            royal_shuffle_button,
            export_csv_button,
            import_csv_button,
        )
    )
    connect_button.pack(pady=10)

    playlist_frame = tk.Frame(root)
    playlist_frame.pack(
        fill="both",
        expand=True,
        padx=20,
        pady=10,
    )

    playlist_scrollbar = tk.Scrollbar(
        playlist_frame,
        orient="vertical",
    )

    playlist_listbox = tk.Listbox(
        playlist_frame,
        width=60,
        height=8,
        state="disabled",
        yscrollcommand=playlist_scrollbar.set,
    )

    playlist_scrollbar.config(
        command=playlist_listbox.yview
    )

    playlist_scrollbar.pack(
        side="right",
        fill="y",
    )

    playlist_listbox.pack(
        side="left",
        fill="both",
        expand=True,
    )

    eligible_playlists = []

    selected_playlist_state = {
        "playlist": None
    }

    client_state = {
        "client": None
    }

    def update_status(message):
        print(f"status: {message}")
        
        status_label.config(
            text=message
        )

        root.update_idletasks()

    def handle_playlist_selection():
        selection = playlist_listbox.curselection()

        if not selection:
            status_label.config(
                text="Select a playlist first"
            )
            return

        selected_playlist = eligible_playlists[selection[0]]
        selected_playlist_state["playlist"] = selected_playlist

        LAST_PLAYLIST_FILE.write_text(
            selected_playlist["id"]
        )

        status_label.config(
            text=f'Selected: {selected_playlist["name"]}'
        )

        royal_shuffle_button.config(
            state="normal"
        )
        export_csv_button.config(
            state="normal"
        )

    playlist_listbox.bind(
        "<Double-Button-1>",
        lambda event: handle_playlist_selection(),
    )

    playlist_listbox.bind(
        "<Button-1>",
        lambda event: playlist_listbox.focus_set(),
    )

    playlist_listbox.bind(
        "<Return>",
        lambda event: handle_playlist_selection(),
    )

    playlist_listbox.bind(
        "<KP_Enter>",
        lambda event: handle_playlist_selection(),
    )

    def handle_royal_shuffle():
        selected_playlist = selected_playlist_state["playlist"]

        if not selected_playlist:
            status_label.config(
                text="Select a playlist first"
            )
            return

        default_name = f'{selected_playlist["name"]} - RANDOM'

        output_playlist_name = simpledialog.askstring(
            "RoyalShuffle",
            "Name your shuffled playlist:",
            initialvalue=default_name,
            parent=root,
        )

        if output_playlist_name is None:
            return

        output_playlist_name = output_playlist_name.strip()

        if not output_playlist_name:
            status_label.config(
                text="Playlist name cannot be empty"
            )
            return

        royal_shuffle_button.config(
            state="disabled"
        )

        status_label.config(
            text=f'Royal Shuffling: {selected_playlist["name"]}...'
        )
        root.update_idletasks()

        try:
            result = royal_shuffle(
                client_state["client"],
                selected_playlist,
                output_playlist_name=output_playlist_name,
                status_callback=update_status,
            )

            status_label.config(
                text=(
                    f'{result["action"].title()}: '
                    f'{result["name"]} '
                    f' • {result["item_count"]} items'
                    + (
                        f' • {result["skipped_item_count"]} local skipped'
                        if result["skipped_item_count"]
                        else ""
                    )
                )
            )

        except SpotifyRetryLaterError as exc:
            log_debug(
                "Royal Shuffle deferred by Spotify; "
                f"exception_type={type(exc).__name__}"
            )
            status_label.config(text=str(exc))

        except Exception as exc:
            print(
                f"Royal Shuffle failed: {exc!r}"
            )
            log_debug(
                "Royal Shuffle failed; "
                f"exception_type={type(exc).__name__}"
            )

            status_label.config(
                text="Royal Shuffle failed. Please try again."
            )

        finally:
            royal_shuffle_button.config(
                state='normal'
            )

    royal_shuffle_button = tk.Button(
        root,
        text="Royal Shuffle",
        width=20,
        state="disabled",
        command=handle_royal_shuffle,
    )
    royal_shuffle_button.pack(pady=10)

    def handle_export_csv():
        selected_playlist = selected_playlist_state["playlist"]

        if not selected_playlist:
            status_label.config(
                text="Select a playlist first"
            )
            return

        destination = choose_csv_destination(
            root,
            selected_playlist["name"],
        )

        if not destination:
            return

        export_csv_button.config(state="disabled")
        status_label.config(
            text=f'Reading: {selected_playlist["name"]}...'
        )
        root.update_idletasks()

        try:
            items = client_state["client"].get_playlist_items(
                selected_playlist["id"]
            )
            row_count = export_playlist_csv(destination, items)
            status_label.config(
                text=(
                    f"Exported {row_count} rows to "
                    f"{destination}"
                )
            )
        except SpotifyRetryLaterError as exc:
            log_debug(
                "CSV export deferred by Spotify; "
                f"exception_type={type(exc).__name__}"
            )
            status_label.config(text=str(exc))
        except Exception as exc:
            print(f"CSV export failed: {exc!r}")
            status_label.config(
                text="CSV export failed. Please try again."
            )
        finally:
            export_csv_button.config(state="normal")

    file_action_frame = tk.Frame(root)
    file_action_frame.pack(pady=10)

    export_csv_button = tk.Button(
        file_action_frame,
        text="Export CSV...",
        width=20,
        state="disabled",
        command=handle_export_csv,
    )
    export_csv_button.pack(side="left", padx=5)

    import_csv_button = create_import_csv_button(
        file_action_frame,
        lambda: import_csv_playlist(
            root,
            client_state["client"],
            status_label,
            import_csv_button,
        ),
    )

    def try_saved_spotify_session():
        log_debug("Checking for saved Spotify session")
        saved_token_data = load_token_data()

        if not saved_token_data:
            log_debug("No saved Spotify session available")
            return

        refresh_token = saved_token_data.get(
            "refresh_token"
        )

        if not refresh_token:
            log_debug("Saved Spotify token data has no refresh token")
            return

        status_label.config(
            text="Reconnecting to Spotify..."
        )

        try:
            refreshed_token_data = refresh_access_token(
                refresh_token
            )

            saved_token_data.update(
                refreshed_token_data
            )

            save_token_data(saved_token_data)

            access_token = saved_token_data[
                "access_token"
            ]

            load_spotify_session(
                access_token,
                status_label,
                connect_button,
                playlist_listbox,
                eligible_playlists,
                client_state,
                selected_playlist_state,
                royal_shuffle_button,
                export_csv_button,
                import_csv_button,
            )

        except SpotifyRetryLaterError as exc:
            log_debug(
                "Saved Spotify session reconnect deferred; "
                f"exception_type={type(exc).__name__}"
            )
            status_label.config(text=str(exc))
            connect_button.config(state="normal")

        except Exception as exc:
            print(
                f"Spotify automatic login failed: {exc!r}"
            )
            log_debug(
                "Saved Spotify session reconnect failed:\n"
                + traceback.format_exc()
            )

            status_label.config(
                text="Not connected"
            )

            connect_button.config(
                state="normal"
            )

    root.after(
        100,
        try_saved_spotify_session,
    )

    root.mainloop()

if __name__ == "__main__":
    main()
