import tkinter as tk
import threading
import traceback

from auth import (
    start_authentication, 
    finish_authentication,
    wait_for_spotify_callback,
    save_token_data,
    load_token_data,
    refresh_access_token,
    clear_token_data,
    log_debug,
)

from spotify_client import SpotifyClient
from royalshuffle import royal_shuffle
from playlist_registry import (
    add_managed_playlist_id,
    add_reviewed_legacy_playlist_id,
    load_managed_playlist_ids,
    load_reviewed_legacy_playlist_ids,
)
from pathlib import Path
from tkinter import messagebox, simpledialog

LAST_PLAYLIST_FILE = Path.home() / ".royalshuffle_last_playlist"
LEGACY_PLAYLIST_DESCRIPTION = (
    "True-randomized copy generated by RoyalShuffle"
)


def review_legacy_playlists(playlists, parent):
    managed_playlist_ids = load_managed_playlist_ids()
    reviewed_playlist_ids = load_reviewed_legacy_playlist_ids()

    candidates = [
        playlist
        for playlist in playlists
        if playlist["id"] not in managed_playlist_ids
        and playlist["id"] not in reviewed_playlist_ids
        and playlist.get("description")
        == LEGACY_PLAYLIST_DESCRIPTION
    ]

    for playlist in candidates:
        recover = messagebox.askyesno(
            "Recover RoyalShuffle playlist?",
            (
                "RoyalShuffle found a possible playlist from an "
                "earlier version.\n\n"
                f'Playlist: {playlist["name"]}\n'
                f'ID: {playlist["id"]}\n\n'
                "Recover this playlist as managed by RoyalShuffle?\n\n"
                "Choose No if this is an ordinary playlist. It will "
                "remain untouched and available as a source."
            ),
            parent=parent,
        )

        if recover:
            add_managed_playlist_id(playlist["id"])

        add_reviewed_legacy_playlist_id(playlist["id"])

def load_spotify_session(
    access_token,
    status_label,
    connect_button,
    playlist_listbox,
    eligible_playlists,
    client_state,
    selected_playlist_state,
    royal_shuffle_button,
):
    log_debug("Creating Spotify client session")
    client = SpotifyClient(access_token)
    client_state["client"] = client

    log_debug("Fetching Spotify playlists")
    playlists = client.get_playlists()
    log_debug(f"Spotify playlist fetch succeeded; count={len(playlists)}")

    review_legacy_playlists(
        playlists,
        playlist_listbox.winfo_toplevel(),
    )

    managed_playlist_ids = load_managed_playlist_ids()
    eligible_playlists.clear()
    eligible_playlists.extend([
        playlist
        for playlist in playlists
        if playlist["id"] not in managed_playlist_ids
    ])

    playlist_listbox.config(state="normal")
    playlist_listbox.delete(0, tk.END)

    for playlist in eligible_playlists:
        playlist_listbox.insert(
            tk.END,
            playlist["name"],
        )

    if LAST_PLAYLIST_FILE.exists():
        last_playlist_id = LAST_PLAYLIST_FILE.read_text().strip()

        for index, playlist in enumerate(eligible_playlists):
            if playlist["id"] == last_playlist_id:
                playlist_listbox.selection_set(index)
                playlist_listbox.activate(index)
                playlist_listbox.see(index)

                selected_playlist_state["playlist"] = playlist

                status_label.config(
                    text=f'Selected: {playlist["name"]}'
                )

                royal_shuffle_button.config(
                    state="normal"
                )

                connect_button.config(state="disabled")
                return

    status_label.config(
        text="Connected to Spotify • Select a playlist"
    )

    connect_button.config(state="disabled")

def connect_spotify(
    status_label,
    connect_button,
    playlist_listbox,
    eligible_playlists,
    client_state,
    selected_playlist_state,
    royal_shuffle_button,
):
    log_debug("Connect Spotify button pressed")

    callback_state = {
        "url": None,
        "error": None,
    }

    def listen_for_callback():
        try:
            callback_state["url"] = wait_for_spotify_callback()
        except Exception as exc:
            callback_state["error"] = exc
            log_debug(
                "Spotify callback listener exception:\n"
                + traceback.format_exc()
            )

    listener_thread = threading.Thread(
        target=listen_for_callback,
        daemon=True,
    )
    listener_thread.start()

    auth_session = start_authentication()
    log_debug("Spotify browser authorization started")

    status_label.config(
        text="Waiting for Spotify authorization..."
    )

    connect_button.config(state="disabled")

    def finish_connection(callback_url):
        print("DEBUG: finishing authentication")
        log_debug("UI received Spotify callback; finishing connection")

        try:
            token_data = finish_authentication(
                callback_url,
                auth_session["code_verifier"],
                auth_session["state"],
            )

            log_debug("OAuth token data returned to UI")
            save_token_data(token_data)

            access_token = token_data["access_token"]

            log_debug("Loading Spotify session after authentication")
            load_spotify_session(
                access_token,
                status_label,
                connect_button,
                playlist_listbox,
                eligible_playlists,
                client_state,
                selected_playlist_state,
                royal_shuffle_button,
            )
            log_debug("Spotify connection completed successfully")

        except Exception as exc:
            print(
                f"Spotify automatic login failed: {exc!r}"
            )
            log_debug(
                "Spotify connection failed:\n"
                + traceback.format_exc()
            )

            clear_token_data()

            status_label.config(
                text="Not connected"
            )

            connect_button.config(
                state="normal"
            )

    def check_for_callback():
        if callback_state["error"] is not None:
            print(
                "Spotify callback listener failed: "
                f'{callback_state["error"]!r}'
            )

            status_label.config(
                text="Spotify connection failed. Click Connect Spotify to retry."
            )

            connect_button.config(state="normal")
            return

        if callback_state["url"] is not None:
            finish_connection(
                callback_state["url"]
            )
            return

        status_label.after(
            100,
            check_for_callback,
        )

    check_for_callback()

def main():
    root = tk.Tk()
    root.title("RoyalShuffle")
    root.geometry()
    root.minsize(500, 500)

    title = tk.Label(
        root,
        text="RoyalShuffle",
        font=("Arial", 24)
    )
    title.pack(pady=40)

    subtitle = tk.Label(
        root,
        text="Transparent, user-controlled Spotify shuffle"
    )
    subtitle.pack(pady=10)
    status_label = tk.Label(
        root,
        text="Not connected"
    )
    status_label.pack(pady=10)

    connect_button = tk.Button(
        root,
        text="Connect Spotify",
        width=20,
        height=2,
        font=("Arial", 11),
        command=lambda: connect_spotify(
            status_label,
            connect_button,
            playlist_listbox,
            eligible_playlists,
            client_state,
            selected_playlist_state,
            royal_shuffle_button,
        )
    )
    connect_button.pack(pady=20)

    playlist_frame = tk.Frame(root)
    playlist_frame.pack(
        fill="both",
        expand=True,
        padx=20,
        pady=10,
    )

    playlist_scrollbar = tk.Scrollbar(
        playlist_frame,
        orient="vertical",
    )

    playlist_listbox = tk.Listbox(
        playlist_frame,
        width=60,
        height=8,
        state="disabled",
        yscrollcommand=playlist_scrollbar.set,
    )

    playlist_scrollbar.config(
        command=playlist_listbox.yview
    )

    playlist_scrollbar.pack(
        side="right",
        fill="y",
    )

    playlist_listbox.pack(
        side="left",
        fill="both",
        expand=True,
    )

    eligible_playlists = []

    selected_playlist_state = {
        "playlist": None
    }

    client_state = {
        "client": None
    }

    def update_status(message):
        print(f"status: {message}")
        
        status_label.config(
            text=message
        )

        root.update_idletasks()

    def handle_playlist_selection():
        selection = playlist_listbox.curselection()

        if not selection:
            status_label.config(
                text="Select a playlist first"
            )
            return

        selected_playlist = eligible_playlists[selection[0]]
        selected_playlist_state["playlist"] = selected_playlist

        LAST_PLAYLIST_FILE.write_text(
            selected_playlist["id"]
        )

        status_label.config(
            text=f'Selected: {selected_playlist["name"]}'
        )

        royal_shuffle_button.config(
            state="normal"
        )

    playlist_listbox.bind(
        "<Double-Button-1>",
        lambda event: handle_playlist_selection(),
    )

    playlist_listbox.bind(
        "<Button-1>",
        lambda event: playlist_listbox.focus_set(),
    )

    playlist_listbox.bind(
        "<Return>",
        lambda event: handle_playlist_selection(),
    )

    playlist_listbox.bind(
        "<KP_Enter>",
        lambda event: handle_playlist_selection(),
    )

    def handle_royal_shuffle():
        selected_playlist = selected_playlist_state["playlist"]

        if not selected_playlist:
            status_label.config(
                text="Select a playlist first"
            )
            return

        default_name = f'{selected_playlist["name"]} - RANDOM'

        output_playlist_name = simpledialog.askstring(
            "RoyalShuffle",
            "Name your shuffled playlist:",
            initialvalue=default_name,
            parent=root,
        )

        if output_playlist_name is None:
            return

        output_playlist_name = output_playlist_name.strip()

        if not output_playlist_name:
            status_label.config(
                text="Playlist name cannot be empty"
            )
            return

        royal_shuffle_button.config(
            state="disabled"
        )

        status_label.config(
            text=f'Royal Shuffling: {selected_playlist["name"]}...'
        )
        root.update_idletasks()

        try:
            result = royal_shuffle(
                client_state["client"],
                selected_playlist,
                output_playlist_name=output_playlist_name,
                status_callback=update_status,
            )

            status_label.config(
                text=(
                    f'{result["action"].title()}: '
                    f'{result["name"]} '
                    f' • {result["item_count"]} items'
                )
            )

        except Exception as exc:
            print(
                f"Royal Shuffle failed: {exc!r}"
            )

            status_label.config(
                text="Royal Shuffle failed. Please try again."
            )

        finally:
            royal_shuffle_button.config(
                state='normal'
            )

    royal_shuffle_button = tk.Button(
        root,
        text="Royal Shuffle",
        width=20,
        state="disabled",
        command=handle_royal_shuffle,
    )
    royal_shuffle_button.pack(pady=10)

    def try_saved_spotify_session():
        log_debug("Checking for saved Spotify session")
        saved_token_data = load_token_data()

        if not saved_token_data:
            log_debug("No saved Spotify session available")
            return

        refresh_token = saved_token_data.get(
            "refresh_token"
        )

        if not refresh_token:
            log_debug("Saved Spotify token data has no refresh token")
            return

        status_label.config(
            text="Reconnecting to Spotify..."
        )

        try:
            refreshed_token_data = refresh_access_token(
                refresh_token
            )

            saved_token_data.update(
                refreshed_token_data
            )

            save_token_data(saved_token_data)

            access_token = saved_token_data[
                "access_token"
            ]

            load_spotify_session(
                access_token,
                status_label,
                connect_button,
                playlist_listbox,
                eligible_playlists,
                client_state,
                selected_playlist_state,
                royal_shuffle_button,
            )

        except Exception as exc:
            print(
                f"Spotify automatic login failed: {exc!r}"
            )
            log_debug(
                "Saved Spotify session reconnect failed:\n"
                + traceback.format_exc()
            )

            status_label.config(
                text="Not connected"
            )

            connect_button.config(
                state="normal"
            )

    root.after(
        100,
        try_saved_spotify_session,
    )

    root.mainloop()

if __name__ == "__main__":
    main()
