package com.royalshuffle.android.output

import com.royalshuffle.android.auth.AccessTokenProvider
import com.royalshuffle.android.domain.model.Playlist
import com.royalshuffle.android.playlist.PlaylistPreferences

class CreateOutputPlaylist(
    private val accessTokenProvider: AccessTokenProvider,
    private val api: OutputPlaylistApi,
    private val preferences: PlaylistPreferences,
    private val shuffler: UriShuffler,
) {
    suspend fun execute(
        source: Playlist,
        onProgress: (OutputProgress) -> Unit = {},
    ): OutputResult {
        val accessToken = accessTokenProvider.getValidAccessToken()
            ?: throw OutputPlaylistException(OutputPlaylistException.Reason.NOT_AUTHENTICATED)

        onProgress(OutputProgress.LoadingItems)
        val uris = loadAllUris(source.id, accessToken)
        onProgress(OutputProgress.Shuffling(uris.size))
        val shuffledUris = shuffler.shuffle(uris.toList())

        onProgress(OutputProgress.CreatingPlaylist)
        val output = api.createPrivatePlaylist(
            name = "${source.name} - RANDOM",
            description = OUTPUT_DESCRIPTION,
            accessToken = accessToken,
        )
        if (output.id == source.id) {
            throw OutputPlaylistException(OutputPlaylistException.Reason.SOURCE_OUTPUT_ID_COLLISION)
        }

        var added = 0
        shuffledUris.chunked(MAX_BATCH_SIZE).forEach { batch ->
            api.addItems(output.id, batch, accessToken)
            added += batch.size
            onProgress(OutputProgress.AddingItems(added, shuffledUris.size))
        }

        preferences.addManagedPlaylistId(output.id)
        return OutputResult(output, shuffledUris.size)
    }

    private suspend fun loadAllUris(sourceId: String, accessToken: String): List<String> =
        buildList {
            var nextUrl: String? = "https://api.spotify.com/v1/playlists/$sourceId/items?limit=50"
            val visitedUrls = mutableSetOf<String>()
            while (nextUrl != null) {
                if (!visitedUrls.add(nextUrl)) {
                    throw OutputPlaylistException(OutputPlaylistException.Reason.INVALID_PAGINATION)
                }
                val page = api.getPlaylistItemsPage(nextUrl, accessToken)
                addAll(page.itemUris.mapNotNull { it?.takeIf(String::isNotBlank) })
                nextUrl = page.nextUrl
            }
        }

    companion object {
        const val OUTPUT_DESCRIPTION = "True-randomized copy generated by RoyalShuffle"
        const val MAX_BATCH_SIZE = 100
    }
}
